version: "3.8"

services:
  db:
    image: postgres:15
    container_name: portfolio_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    # build: direktifi KALDIRILDI
    image: yunuscanunal/portfolio-backend:latest # İmajın Docker Hub'dan çekileceği belirtildi
    container_name: portfolio_backend
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    #ports:
    #  - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: portfolio_frontend
    environment:
      - REACT_APP_API_URL=/
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
