version: "3.8"

services:
  db:
    image: postgres:15
    container_name: portfolio_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    # build: direktifi KALDIRILDI
    image: yunuscanunal/portfolio-backend:latest # İmajın Docker Hub'dan çekileceği belirtildi
    container_name: portfolio_backend
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/portfolio_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    # build: direktifi KALDIRILDI
    image: yunuscanunal/portfolio-frontend:latest # İmajın Docker Hub'dan çekileceği belirtildi
    container_name: portfolio_frontend
    environment:
      # API adresini de doğru, public adresle güncelledik
      - REACT_APP_API_URL=http://yunuscanunal.me:8080
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
