version: "3.8"

services:
  db:
    image: postgres:15
    container_name: portfolio_db
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: portfolio_backend
    environment:
      ADMIN_USERNAME: admin
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/portfolio_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin1234
      JWT_SECRET: MySuperSecretKeyForJWT1234567890
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: portfolio_frontend
    environment:
      - REACT_APP_API_URL=http://yunuscanunal:8080
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
